//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Метаданные связи EDM

[assembly: EdmRelationshipAttribute("TextClassificatorModel", "FK_Allolog_Word", "Word", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TextClassifierLib.Word), "Allolog", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TextClassifierLib.Allolog), true)]
[assembly: EdmRelationshipAttribute("TextClassificatorModel", "FK_WordCandidatesInTheme_Theme", "Theme", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TextClassifierLib.Theme), "WordCandidatesInTheme", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TextClassifierLib.WordCandidatesInTheme), true)]
[assembly: EdmRelationshipAttribute("TextClassificatorModel", "FK_WordInTheme_Theme", "Theme", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TextClassifierLib.Theme), "WordInTheme", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TextClassifierLib.WordInTheme), true)]
[assembly: EdmRelationshipAttribute("TextClassificatorModel", "FK_WordNotInTheme_Theme", "Theme", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TextClassifierLib.Theme), "WordNotInTheme", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TextClassifierLib.WordNotInTheme), true)]
[assembly: EdmRelationshipAttribute("TextClassificatorModel", "FK_WordCandidatesInTheme_Word", "Word", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TextClassifierLib.Word), "WordCandidatesInTheme", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TextClassifierLib.WordCandidatesInTheme), true)]
[assembly: EdmRelationshipAttribute("TextClassificatorModel", "FK_WordInTheme_Word", "Word", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TextClassifierLib.Word), "WordInTheme", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TextClassifierLib.WordInTheme), true)]
[assembly: EdmRelationshipAttribute("TextClassificatorModel", "FK_WordNotInTheme_Word", "Word", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TextClassifierLib.Word), "WordNotInTheme", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TextClassifierLib.WordNotInTheme), true)]

#endregion

namespace TextClassifierLib
{
    #region Контексты
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    public partial class TextClassificatorEntities : ObjectContext
    {
        #region Конструкторы
    
        /// <summary>
        /// Инициализирует новый объект TextClassificatorEntities, используя строку соединения из раздела "TextClassificatorEntities" файла конфигурации приложения.
        /// </summary>
        public TextClassificatorEntities() : base("name=TextClassificatorEntities", "TextClassificatorEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта TextClassificatorEntities.
        /// </summary>
        public TextClassificatorEntities(string connectionString) : base(connectionString, "TextClassificatorEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта TextClassificatorEntities.
        /// </summary>
        public TextClassificatorEntities(EntityConnection connection) : base(connection, "TextClassificatorEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Разделяемые методы
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Свойства ObjectSet
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<Allolog> Allolog
        {
            get
            {
                if ((_Allolog == null))
                {
                    _Allolog = base.CreateObjectSet<Allolog>("Allolog");
                }
                return _Allolog;
            }
        }
        private ObjectSet<Allolog> _Allolog;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<Theme> Theme
        {
            get
            {
                if ((_Theme == null))
                {
                    _Theme = base.CreateObjectSet<Theme>("Theme");
                }
                return _Theme;
            }
        }
        private ObjectSet<Theme> _Theme;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<Word> Word
        {
            get
            {
                if ((_Word == null))
                {
                    _Word = base.CreateObjectSet<Word>("Word");
                }
                return _Word;
            }
        }
        private ObjectSet<Word> _Word;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<WordCandidatesInTheme> WordCandidatesInTheme
        {
            get
            {
                if ((_WordCandidatesInTheme == null))
                {
                    _WordCandidatesInTheme = base.CreateObjectSet<WordCandidatesInTheme>("WordCandidatesInTheme");
                }
                return _WordCandidatesInTheme;
            }
        }
        private ObjectSet<WordCandidatesInTheme> _WordCandidatesInTheme;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<WordInTheme> WordInTheme
        {
            get
            {
                if ((_WordInTheme == null))
                {
                    _WordInTheme = base.CreateObjectSet<WordInTheme>("WordInTheme");
                }
                return _WordInTheme;
            }
        }
        private ObjectSet<WordInTheme> _WordInTheme;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<WordNotInTheme> WordNotInTheme
        {
            get
            {
                if ((_WordNotInTheme == null))
                {
                    _WordNotInTheme = base.CreateObjectSet<WordNotInTheme>("WordNotInTheme");
                }
                return _WordNotInTheme;
            }
        }
        private ObjectSet<WordNotInTheme> _WordNotInTheme;

        #endregion
        #region Методы AddTo
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet Allolog. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToAllolog(Allolog allolog)
        {
            base.AddObject("Allolog", allolog);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet Theme. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToTheme(Theme theme)
        {
            base.AddObject("Theme", theme);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet Word. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToWord(Word word)
        {
            base.AddObject("Word", word);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet WordCandidatesInTheme. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToWordCandidatesInTheme(WordCandidatesInTheme wordCandidatesInTheme)
        {
            base.AddObject("WordCandidatesInTheme", wordCandidatesInTheme);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet WordInTheme. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToWordInTheme(WordInTheme wordInTheme)
        {
            base.AddObject("WordInTheme", wordInTheme);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet WordNotInTheme. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToWordNotInTheme(WordNotInTheme wordNotInTheme)
        {
            base.AddObject("WordNotInTheme", wordNotInTheme);
        }

        #endregion
    }
    

    #endregion
    
    #region Сущности
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TextClassificatorModel", Name="Allolog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Allolog : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта Allolog.
        /// </summary>
        /// <param name="allolog_id">Исходное значение свойства Allolog_id.</param>
        /// <param name="allolog_name">Исходное значение свойства Allolog_name.</param>
        /// <param name="word_id">Исходное значение свойства Word_id.</param>
        /// <param name="system_InsDT">Исходное значение свойства System_InsDT.</param>
        public static Allolog CreateAllolog(global::System.Int64 allolog_id, global::System.String allolog_name, global::System.Int64 word_id, global::System.DateTime system_InsDT)
        {
            Allolog allolog = new Allolog();
            allolog.Allolog_id = allolog_id;
            allolog.Allolog_name = allolog_name;
            allolog.Word_id = word_id;
            allolog.System_InsDT = system_InsDT;
            return allolog;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Allolog_id
        {
            get
            {
                return _Allolog_id;
            }
            set
            {
                if (_Allolog_id != value)
                {
                    OnAllolog_idChanging(value);
                    ReportPropertyChanging("Allolog_id");
                    _Allolog_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Allolog_id");
                    OnAllolog_idChanged();
                }
            }
        }
        private global::System.Int64 _Allolog_id;
        partial void OnAllolog_idChanging(global::System.Int64 value);
        partial void OnAllolog_idChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Allolog_name
        {
            get
            {
                return _Allolog_name;
            }
            set
            {
                OnAllolog_nameChanging(value);
                ReportPropertyChanging("Allolog_name");
                _Allolog_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Allolog_name");
                OnAllolog_nameChanged();
            }
        }
        private global::System.String _Allolog_name;
        partial void OnAllolog_nameChanging(global::System.String value);
        partial void OnAllolog_nameChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Word_id
        {
            get
            {
                return _Word_id;
            }
            set
            {
                OnWord_idChanging(value);
                ReportPropertyChanging("Word_id");
                _Word_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Word_id");
                OnWord_idChanged();
            }
        }
        private global::System.Int64 _Word_id;
        partial void OnWord_idChanging(global::System.Int64 value);
        partial void OnWord_idChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime System_InsDT
        {
            get
            {
                return _System_InsDT;
            }
            set
            {
                OnSystem_InsDTChanging(value);
                ReportPropertyChanging("System_InsDT");
                _System_InsDT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("System_InsDT");
                OnSystem_InsDTChanged();
            }
        }
        private global::System.DateTime _System_InsDT;
        partial void OnSystem_InsDTChanging(global::System.DateTime value);
        partial void OnSystem_InsDTChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TextClassificatorModel", "FK_Allolog_Word", "Word")]
        public Word Word
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Word>("TextClassificatorModel.FK_Allolog_Word", "Word").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Word>("TextClassificatorModel.FK_Allolog_Word", "Word").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Word> WordReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Word>("TextClassificatorModel.FK_Allolog_Word", "Word");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Word>("TextClassificatorModel.FK_Allolog_Word", "Word", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TextClassificatorModel", Name="Theme")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Theme : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта Theme.
        /// </summary>
        /// <param name="theme_id">Исходное значение свойства Theme_id.</param>
        /// <param name="theme_name">Исходное значение свойства Theme_name.</param>
        /// <param name="system_InsDT">Исходное значение свойства System_InsDT.</param>
        /// <param name="theme_caption">Исходное значение свойства Theme_caption.</param>
        public static Theme CreateTheme(global::System.Int64 theme_id, global::System.String theme_name, global::System.DateTime system_InsDT, global::System.String theme_caption)
        {
            Theme theme = new Theme();
            theme.Theme_id = theme_id;
            theme.Theme_name = theme_name;
            theme.System_InsDT = system_InsDT;
            theme.Theme_caption = theme_caption;
            return theme;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Theme_id
        {
            get
            {
                return _Theme_id;
            }
            set
            {
                if (_Theme_id != value)
                {
                    OnTheme_idChanging(value);
                    ReportPropertyChanging("Theme_id");
                    _Theme_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Theme_id");
                    OnTheme_idChanged();
                }
            }
        }
        private global::System.Int64 _Theme_id;
        partial void OnTheme_idChanging(global::System.Int64 value);
        partial void OnTheme_idChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Theme_name
        {
            get
            {
                return _Theme_name;
            }
            set
            {
                OnTheme_nameChanging(value);
                ReportPropertyChanging("Theme_name");
                _Theme_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Theme_name");
                OnTheme_nameChanged();
            }
        }
        private global::System.String _Theme_name;
        partial void OnTheme_nameChanging(global::System.String value);
        partial void OnTheme_nameChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime System_InsDT
        {
            get
            {
                return _System_InsDT;
            }
            set
            {
                OnSystem_InsDTChanging(value);
                ReportPropertyChanging("System_InsDT");
                _System_InsDT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("System_InsDT");
                OnSystem_InsDTChanged();
            }
        }
        private global::System.DateTime _System_InsDT;
        partial void OnSystem_InsDTChanging(global::System.DateTime value);
        partial void OnSystem_InsDTChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Theme_caption
        {
            get
            {
                return _Theme_caption;
            }
            set
            {
                OnTheme_captionChanging(value);
                ReportPropertyChanging("Theme_caption");
                _Theme_caption = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Theme_caption");
                OnTheme_captionChanged();
            }
        }
        private global::System.String _Theme_caption;
        partial void OnTheme_captionChanging(global::System.String value);
        partial void OnTheme_captionChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TextClassificatorModel", "FK_WordCandidatesInTheme_Theme", "WordCandidatesInTheme")]
        public EntityCollection<WordCandidatesInTheme> WordCandidatesInTheme
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<WordCandidatesInTheme>("TextClassificatorModel.FK_WordCandidatesInTheme_Theme", "WordCandidatesInTheme");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<WordCandidatesInTheme>("TextClassificatorModel.FK_WordCandidatesInTheme_Theme", "WordCandidatesInTheme", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TextClassificatorModel", "FK_WordInTheme_Theme", "WordInTheme")]
        public EntityCollection<WordInTheme> WordInTheme
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<WordInTheme>("TextClassificatorModel.FK_WordInTheme_Theme", "WordInTheme");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<WordInTheme>("TextClassificatorModel.FK_WordInTheme_Theme", "WordInTheme", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TextClassificatorModel", "FK_WordNotInTheme_Theme", "WordNotInTheme")]
        public EntityCollection<WordNotInTheme> WordNotInTheme
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<WordNotInTheme>("TextClassificatorModel.FK_WordNotInTheme_Theme", "WordNotInTheme");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<WordNotInTheme>("TextClassificatorModel.FK_WordNotInTheme_Theme", "WordNotInTheme", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TextClassificatorModel", Name="Word")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Word : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта Word.
        /// </summary>
        /// <param name="word_id">Исходное значение свойства Word_id.</param>
        /// <param name="word_name">Исходное значение свойства Word_name.</param>
        /// <param name="system_InsDT">Исходное значение свойства System_InsDT.</param>
        public static Word CreateWord(global::System.Int64 word_id, global::System.String word_name, global::System.DateTime system_InsDT)
        {
            Word word = new Word();
            word.Word_id = word_id;
            word.Word_name = word_name;
            word.System_InsDT = system_InsDT;
            return word;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Word_id
        {
            get
            {
                return _Word_id;
            }
            set
            {
                if (_Word_id != value)
                {
                    OnWord_idChanging(value);
                    ReportPropertyChanging("Word_id");
                    _Word_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Word_id");
                    OnWord_idChanged();
                }
            }
        }
        private global::System.Int64 _Word_id;
        partial void OnWord_idChanging(global::System.Int64 value);
        partial void OnWord_idChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Word_name
        {
            get
            {
                return _Word_name;
            }
            set
            {
                OnWord_nameChanging(value);
                ReportPropertyChanging("Word_name");
                _Word_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Word_name");
                OnWord_nameChanged();
            }
        }
        private global::System.String _Word_name;
        partial void OnWord_nameChanging(global::System.String value);
        partial void OnWord_nameChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime System_InsDT
        {
            get
            {
                return _System_InsDT;
            }
            set
            {
                OnSystem_InsDTChanging(value);
                ReportPropertyChanging("System_InsDT");
                _System_InsDT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("System_InsDT");
                OnSystem_InsDTChanged();
            }
        }
        private global::System.DateTime _System_InsDT;
        partial void OnSystem_InsDTChanging(global::System.DateTime value);
        partial void OnSystem_InsDTChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TextClassificatorModel", "FK_Allolog_Word", "Allolog")]
        public EntityCollection<Allolog> Allolog
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Allolog>("TextClassificatorModel.FK_Allolog_Word", "Allolog");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Allolog>("TextClassificatorModel.FK_Allolog_Word", "Allolog", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TextClassificatorModel", "FK_WordCandidatesInTheme_Word", "WordCandidatesInTheme")]
        public EntityCollection<WordCandidatesInTheme> WordCandidatesInTheme
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<WordCandidatesInTheme>("TextClassificatorModel.FK_WordCandidatesInTheme_Word", "WordCandidatesInTheme");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<WordCandidatesInTheme>("TextClassificatorModel.FK_WordCandidatesInTheme_Word", "WordCandidatesInTheme", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TextClassificatorModel", "FK_WordInTheme_Word", "WordInTheme")]
        public EntityCollection<WordInTheme> WordInTheme
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<WordInTheme>("TextClassificatorModel.FK_WordInTheme_Word", "WordInTheme");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<WordInTheme>("TextClassificatorModel.FK_WordInTheme_Word", "WordInTheme", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TextClassificatorModel", "FK_WordNotInTheme_Word", "WordNotInTheme")]
        public EntityCollection<WordNotInTheme> WordNotInTheme
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<WordNotInTheme>("TextClassificatorModel.FK_WordNotInTheme_Word", "WordNotInTheme");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<WordNotInTheme>("TextClassificatorModel.FK_WordNotInTheme_Word", "WordNotInTheme", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TextClassificatorModel", Name="WordCandidatesInTheme")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WordCandidatesInTheme : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта WordCandidatesInTheme.
        /// </summary>
        /// <param name="wordCandidatesInTheme_id">Исходное значение свойства WordCandidatesInTheme_id.</param>
        /// <param name="word_id">Исходное значение свойства Word_id.</param>
        /// <param name="theme_id">Исходное значение свойства Theme_id.</param>
        /// <param name="wordCandidatesInTheme_Visible">Исходное значение свойства WordCandidatesInTheme_Visible.</param>
        /// <param name="system_InsDT">Исходное значение свойства System_InsDT.</param>
        public static WordCandidatesInTheme CreateWordCandidatesInTheme(global::System.Int64 wordCandidatesInTheme_id, global::System.Int64 word_id, global::System.Int64 theme_id, global::System.Boolean wordCandidatesInTheme_Visible, global::System.DateTime system_InsDT)
        {
            WordCandidatesInTheme wordCandidatesInTheme = new WordCandidatesInTheme();
            wordCandidatesInTheme.WordCandidatesInTheme_id = wordCandidatesInTheme_id;
            wordCandidatesInTheme.Word_id = word_id;
            wordCandidatesInTheme.Theme_id = theme_id;
            wordCandidatesInTheme.WordCandidatesInTheme_Visible = wordCandidatesInTheme_Visible;
            wordCandidatesInTheme.System_InsDT = system_InsDT;
            return wordCandidatesInTheme;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 WordCandidatesInTheme_id
        {
            get
            {
                return _WordCandidatesInTheme_id;
            }
            set
            {
                if (_WordCandidatesInTheme_id != value)
                {
                    OnWordCandidatesInTheme_idChanging(value);
                    ReportPropertyChanging("WordCandidatesInTheme_id");
                    _WordCandidatesInTheme_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("WordCandidatesInTheme_id");
                    OnWordCandidatesInTheme_idChanged();
                }
            }
        }
        private global::System.Int64 _WordCandidatesInTheme_id;
        partial void OnWordCandidatesInTheme_idChanging(global::System.Int64 value);
        partial void OnWordCandidatesInTheme_idChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Word_id
        {
            get
            {
                return _Word_id;
            }
            set
            {
                OnWord_idChanging(value);
                ReportPropertyChanging("Word_id");
                _Word_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Word_id");
                OnWord_idChanged();
            }
        }
        private global::System.Int64 _Word_id;
        partial void OnWord_idChanging(global::System.Int64 value);
        partial void OnWord_idChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Theme_id
        {
            get
            {
                return _Theme_id;
            }
            set
            {
                OnTheme_idChanging(value);
                ReportPropertyChanging("Theme_id");
                _Theme_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Theme_id");
                OnTheme_idChanged();
            }
        }
        private global::System.Int64 _Theme_id;
        partial void OnTheme_idChanging(global::System.Int64 value);
        partial void OnTheme_idChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean WordCandidatesInTheme_Visible
        {
            get
            {
                return _WordCandidatesInTheme_Visible;
            }
            set
            {
                OnWordCandidatesInTheme_VisibleChanging(value);
                ReportPropertyChanging("WordCandidatesInTheme_Visible");
                _WordCandidatesInTheme_Visible = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WordCandidatesInTheme_Visible");
                OnWordCandidatesInTheme_VisibleChanged();
            }
        }
        private global::System.Boolean _WordCandidatesInTheme_Visible;
        partial void OnWordCandidatesInTheme_VisibleChanging(global::System.Boolean value);
        partial void OnWordCandidatesInTheme_VisibleChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime System_InsDT
        {
            get
            {
                return _System_InsDT;
            }
            set
            {
                OnSystem_InsDTChanging(value);
                ReportPropertyChanging("System_InsDT");
                _System_InsDT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("System_InsDT");
                OnSystem_InsDTChanged();
            }
        }
        private global::System.DateTime _System_InsDT;
        partial void OnSystem_InsDTChanging(global::System.DateTime value);
        partial void OnSystem_InsDTChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TextClassificatorModel", "FK_WordCandidatesInTheme_Theme", "Theme")]
        public Theme Theme
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme>("TextClassificatorModel.FK_WordCandidatesInTheme_Theme", "Theme").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme>("TextClassificatorModel.FK_WordCandidatesInTheme_Theme", "Theme").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Theme> ThemeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme>("TextClassificatorModel.FK_WordCandidatesInTheme_Theme", "Theme");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Theme>("TextClassificatorModel.FK_WordCandidatesInTheme_Theme", "Theme", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TextClassificatorModel", "FK_WordCandidatesInTheme_Word", "Word")]
        public Word Word
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Word>("TextClassificatorModel.FK_WordCandidatesInTheme_Word", "Word").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Word>("TextClassificatorModel.FK_WordCandidatesInTheme_Word", "Word").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Word> WordReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Word>("TextClassificatorModel.FK_WordCandidatesInTheme_Word", "Word");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Word>("TextClassificatorModel.FK_WordCandidatesInTheme_Word", "Word", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TextClassificatorModel", Name="WordInTheme")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WordInTheme : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта WordInTheme.
        /// </summary>
        /// <param name="wordInTheme_id">Исходное значение свойства WordInTheme_id.</param>
        /// <param name="wordInTheme_isLexicalizedWord">Исходное значение свойства WordInTheme_isLexicalizedWord.</param>
        /// <param name="word_id">Исходное значение свойства Word_id.</param>
        /// <param name="theme_id">Исходное значение свойства Theme_id.</param>
        /// <param name="system_InsDT">Исходное значение свойства System_InsDT.</param>
        public static WordInTheme CreateWordInTheme(global::System.Int64 wordInTheme_id, global::System.Boolean wordInTheme_isLexicalizedWord, global::System.Int64 word_id, global::System.Int64 theme_id, global::System.DateTime system_InsDT)
        {
            WordInTheme wordInTheme = new WordInTheme();
            wordInTheme.WordInTheme_id = wordInTheme_id;
            wordInTheme.WordInTheme_isLexicalizedWord = wordInTheme_isLexicalizedWord;
            wordInTheme.Word_id = word_id;
            wordInTheme.Theme_id = theme_id;
            wordInTheme.System_InsDT = system_InsDT;
            return wordInTheme;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 WordInTheme_id
        {
            get
            {
                return _WordInTheme_id;
            }
            set
            {
                if (_WordInTheme_id != value)
                {
                    OnWordInTheme_idChanging(value);
                    ReportPropertyChanging("WordInTheme_id");
                    _WordInTheme_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("WordInTheme_id");
                    OnWordInTheme_idChanged();
                }
            }
        }
        private global::System.Int64 _WordInTheme_id;
        partial void OnWordInTheme_idChanging(global::System.Int64 value);
        partial void OnWordInTheme_idChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean WordInTheme_isLexicalizedWord
        {
            get
            {
                return _WordInTheme_isLexicalizedWord;
            }
            set
            {
                OnWordInTheme_isLexicalizedWordChanging(value);
                ReportPropertyChanging("WordInTheme_isLexicalizedWord");
                _WordInTheme_isLexicalizedWord = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WordInTheme_isLexicalizedWord");
                OnWordInTheme_isLexicalizedWordChanged();
            }
        }
        private global::System.Boolean _WordInTheme_isLexicalizedWord;
        partial void OnWordInTheme_isLexicalizedWordChanging(global::System.Boolean value);
        partial void OnWordInTheme_isLexicalizedWordChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Word_id
        {
            get
            {
                return _Word_id;
            }
            set
            {
                OnWord_idChanging(value);
                ReportPropertyChanging("Word_id");
                _Word_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Word_id");
                OnWord_idChanged();
            }
        }
        private global::System.Int64 _Word_id;
        partial void OnWord_idChanging(global::System.Int64 value);
        partial void OnWord_idChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Theme_id
        {
            get
            {
                return _Theme_id;
            }
            set
            {
                OnTheme_idChanging(value);
                ReportPropertyChanging("Theme_id");
                _Theme_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Theme_id");
                OnTheme_idChanged();
            }
        }
        private global::System.Int64 _Theme_id;
        partial void OnTheme_idChanging(global::System.Int64 value);
        partial void OnTheme_idChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime System_InsDT
        {
            get
            {
                return _System_InsDT;
            }
            set
            {
                OnSystem_InsDTChanging(value);
                ReportPropertyChanging("System_InsDT");
                _System_InsDT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("System_InsDT");
                OnSystem_InsDTChanged();
            }
        }
        private global::System.DateTime _System_InsDT;
        partial void OnSystem_InsDTChanging(global::System.DateTime value);
        partial void OnSystem_InsDTChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TextClassificatorModel", "FK_WordInTheme_Theme", "Theme")]
        public Theme Theme
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme>("TextClassificatorModel.FK_WordInTheme_Theme", "Theme").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme>("TextClassificatorModel.FK_WordInTheme_Theme", "Theme").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Theme> ThemeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme>("TextClassificatorModel.FK_WordInTheme_Theme", "Theme");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Theme>("TextClassificatorModel.FK_WordInTheme_Theme", "Theme", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TextClassificatorModel", "FK_WordInTheme_Word", "Word")]
        public Word Word
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Word>("TextClassificatorModel.FK_WordInTheme_Word", "Word").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Word>("TextClassificatorModel.FK_WordInTheme_Word", "Word").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Word> WordReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Word>("TextClassificatorModel.FK_WordInTheme_Word", "Word");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Word>("TextClassificatorModel.FK_WordInTheme_Word", "Word", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TextClassificatorModel", Name="WordNotInTheme")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WordNotInTheme : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта WordNotInTheme.
        /// </summary>
        /// <param name="wordNotInTheme_id">Исходное значение свойства WordNotInTheme_id.</param>
        /// <param name="word_id">Исходное значение свойства Word_id.</param>
        /// <param name="theme_id">Исходное значение свойства Theme_id.</param>
        /// <param name="system_InsDT">Исходное значение свойства System_InsDT.</param>
        public static WordNotInTheme CreateWordNotInTheme(global::System.Int64 wordNotInTheme_id, global::System.Int64 word_id, global::System.Int64 theme_id, global::System.DateTime system_InsDT)
        {
            WordNotInTheme wordNotInTheme = new WordNotInTheme();
            wordNotInTheme.WordNotInTheme_id = wordNotInTheme_id;
            wordNotInTheme.Word_id = word_id;
            wordNotInTheme.Theme_id = theme_id;
            wordNotInTheme.System_InsDT = system_InsDT;
            return wordNotInTheme;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 WordNotInTheme_id
        {
            get
            {
                return _WordNotInTheme_id;
            }
            set
            {
                if (_WordNotInTheme_id != value)
                {
                    OnWordNotInTheme_idChanging(value);
                    ReportPropertyChanging("WordNotInTheme_id");
                    _WordNotInTheme_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("WordNotInTheme_id");
                    OnWordNotInTheme_idChanged();
                }
            }
        }
        private global::System.Int64 _WordNotInTheme_id;
        partial void OnWordNotInTheme_idChanging(global::System.Int64 value);
        partial void OnWordNotInTheme_idChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Word_id
        {
            get
            {
                return _Word_id;
            }
            set
            {
                OnWord_idChanging(value);
                ReportPropertyChanging("Word_id");
                _Word_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Word_id");
                OnWord_idChanged();
            }
        }
        private global::System.Int64 _Word_id;
        partial void OnWord_idChanging(global::System.Int64 value);
        partial void OnWord_idChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Theme_id
        {
            get
            {
                return _Theme_id;
            }
            set
            {
                OnTheme_idChanging(value);
                ReportPropertyChanging("Theme_id");
                _Theme_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Theme_id");
                OnTheme_idChanged();
            }
        }
        private global::System.Int64 _Theme_id;
        partial void OnTheme_idChanging(global::System.Int64 value);
        partial void OnTheme_idChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime System_InsDT
        {
            get
            {
                return _System_InsDT;
            }
            set
            {
                OnSystem_InsDTChanging(value);
                ReportPropertyChanging("System_InsDT");
                _System_InsDT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("System_InsDT");
                OnSystem_InsDTChanged();
            }
        }
        private global::System.DateTime _System_InsDT;
        partial void OnSystem_InsDTChanging(global::System.DateTime value);
        partial void OnSystem_InsDTChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TextClassificatorModel", "FK_WordNotInTheme_Theme", "Theme")]
        public Theme Theme
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme>("TextClassificatorModel.FK_WordNotInTheme_Theme", "Theme").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme>("TextClassificatorModel.FK_WordNotInTheme_Theme", "Theme").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Theme> ThemeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme>("TextClassificatorModel.FK_WordNotInTheme_Theme", "Theme");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Theme>("TextClassificatorModel.FK_WordNotInTheme_Theme", "Theme", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TextClassificatorModel", "FK_WordNotInTheme_Word", "Word")]
        public Word Word
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Word>("TextClassificatorModel.FK_WordNotInTheme_Word", "Word").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Word>("TextClassificatorModel.FK_WordNotInTheme_Word", "Word").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Word> WordReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Word>("TextClassificatorModel.FK_WordNotInTheme_Word", "Word");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Word>("TextClassificatorModel.FK_WordNotInTheme_Word", "Word", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
