//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextClassifierLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextClassifierLib.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;гараж&quot; Weight=&quot;0.502864862700724&quot;&gt;
        ///&lt;Allolog Form=&quot;гараж&quot;/&gt;
        ///&lt;Allolog Form=&quot;гаража&quot;/&gt;
        ///&lt;Allolog Form=&quot;гаражи&quot;/&gt;
        ///&lt;Allolog Form=&quot;гараже&quot;/&gt;
        ///&lt;Allolog Form=&quot;гаражах&quot;/&gt;
        ///&lt;Allolog Form=&quot;гаражу&quot;/&gt;
        ///&lt;Allolog Form=&quot;гаражом&quot;/&gt;
        ///&lt;Allolog Form=&quot;гаражей&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;автомобил&quot; Weight=&quot;1.26968561685551&quot;&gt;
        ///&lt;Allolog Form=&quot;автомобилей&quot;/&gt;
        ///&lt;Allolog Form=&quot;автомобиль&quot;/&gt;
        ///&lt;Allolog Form=&quot;автомобиля&quot;/&gt;
        ///&lt;Allolog Form=&quot;автомобилях&quot;/&gt;
        ///&lt;Allolog Form=&quot;автомобилем&quot;/&gt;
        ///&lt;Allolog Form=&quot;автомобилю&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string auto_export {
            get {
                return ResourceManager.GetString("auto_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;экологическ&quot; Weight=&quot;0.522500124124653&quot;&gt;
        ///&lt;Allolog Form=&quot;экологические&quot;/&gt;
        ///&lt;Allolog Form=&quot;экологически&quot;/&gt;
        ///&lt;Allolog Form=&quot;экологического&quot;/&gt;
        ///&lt;Allolog Form=&quot;экологических&quot;/&gt;
        ///&lt;Allolog Form=&quot;экологической&quot;/&gt;
        ///&lt;Allolog Form=&quot;экологическое&quot;/&gt;
        ///&lt;Allolog Form=&quot;экологическими&quot;/&gt;
        ///&lt;Allolog Form=&quot;экологическая&quot;/&gt;
        ///&lt;Allolog Form=&quot;экологическую&quot;/&gt;
        ///&lt;Allolog Form=&quot;экологическим&quot;/&gt;
        ///&lt;Allolog Form=&quot;экологический&quot;/&gt;
        ///&lt;Allolog Form=&quot;экологическом&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;выживаем&quot; Weight=&quot;0.0538866 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string biologiy_export {
            get {
                return ResourceManager.GetString("biologiy_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;гигант&quot; Weight=&quot;0.0342889063017964&quot;&gt;
        ///&lt;Allolog Form=&quot;гигантов&quot;/&gt;
        ///&lt;Allolog Form=&quot;гигант&quot;/&gt;
        ///&lt;Allolog Form=&quot;гиганты&quot;/&gt;
        ///&lt;Allolog Form=&quot;гигантам&quot;/&gt;
        ///&lt;Allolog Form=&quot;гигантом&quot;/&gt;
        ///&lt;Allolog Form=&quot;гиганта&quot;/&gt;
        ///&lt;Allolog Form=&quot;гиганту&quot;/&gt;
        ///&lt;Allolog Form=&quot;гигантами&quot;/&gt;
        ///&lt;Allolog Form=&quot;гигантах&quot;/&gt;
        ///&lt;Allolog Form=&quot;гиганте&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;атмосфер&quot; Weight=&quot;0.108782645962869&quot;&gt;
        ///&lt;Allolog Form=&quot;атмосферу&quot;/&gt;
        ///&lt;Allolog Form=&quot;атмосфер&quot;/&gt;
        ///&lt;Allolog Form=&quot;атмосфере&quot;/&gt;
        ///&lt;Allolog Form=&quot;атмосферы&quot;/&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cosmos_export {
            get {
                return ResourceManager.GetString("Cosmos_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;масл&quot; Weight=&quot;2.29756888708991&quot;&gt;
        ///&lt;Allolog Form=&quot;масл&quot;/&gt;
        ///&lt;Allolog Form=&quot;масло&quot;/&gt;
        ///&lt;Allolog Form=&quot;масла&quot;/&gt;
        ///&lt;Allolog Form=&quot;маслу&quot;/&gt;
        ///&lt;Allolog Form=&quot;масля&quot;/&gt;
        ///&lt;Allolog Form=&quot;маслами&quot;/&gt;
        ///&lt;Allolog Form=&quot;маслом&quot;/&gt;
        ///&lt;Allolog Form=&quot;масле&quot;/&gt;
        ///&lt;Allolog Form=&quot;маслам&quot;/&gt;
        ///&lt;Allolog Form=&quot;масли&quot;/&gt;
        ///&lt;Allolog Form=&quot;маслах&quot;/&gt;
        ///&lt;Allolog Form=&quot;маслов&quot;/&gt;
        ///&lt;Allolog Form=&quot;маслиев&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;килограмм&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;килограммов&quot;/&gt;
        ///&lt;Allolog Form=&quot;килограмм&quot;/&gt;
        ///&lt;Allolog Form [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string culinariy_export {
            get {
                return ResourceManager.GetString("culinariy_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;культур&quot; Weight=&quot;0.837017917847888&quot;&gt;
        ///&lt;Allolog Form=&quot;культура&quot;/&gt;
        ///&lt;Allolog Form=&quot;культуры&quot;/&gt;
        ///&lt;Allolog Form=&quot;культуре&quot;/&gt;
        ///&lt;Allolog Form=&quot;культуру&quot;/&gt;
        ///&lt;Allolog Form=&quot;культурах&quot;/&gt;
        ///&lt;Allolog Form=&quot;культур&quot;/&gt;
        ///&lt;Allolog Form=&quot;культурами&quot;/&gt;
        ///&lt;Allolog Form=&quot;культурам&quot;/&gt;
        ///&lt;Allolog Form=&quot;культурой&quot;/&gt;
        ///&lt;Allolog Form=&quot;культуро&quot;/&gt;
        ///&lt;Allolog Form=&quot;культурою&quot;/&gt;
        ///&lt;Allolog Form=&quot;культури&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;жанр&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;жанра&quot;/&gt;
        ///&lt;Allolog Form=&quot;жанров&quot;/&gt;
        ///&lt;Allolog Form= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cultura_export {
            get {
                return ResourceManager.GetString("cultura_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;промышлен&quot; Weight=&quot;0.542620594746153&quot;&gt;
        ///&lt;Allolog Form=&quot;промышленности&quot;/&gt;
        ///&lt;Allolog Form=&quot;промышленно&quot;/&gt;
        ///&lt;Allolog Form=&quot;промышленность&quot;/&gt;
        ///&lt;Allolog Form=&quot;промышленного&quot;/&gt;
        ///&lt;Allolog Form=&quot;промышленные&quot;/&gt;
        ///&lt;Allolog Form=&quot;промышленное&quot;/&gt;
        ///&lt;Allolog Form=&quot;промышленными&quot;/&gt;
        ///&lt;Allolog Form=&quot;промышленный&quot;/&gt;
        ///&lt;Allolog Form=&quot;промышленной&quot;/&gt;
        ///&lt;Allolog Form=&quot;промышлен&quot;/&gt;
        ///&lt;Allolog Form=&quot;промышленностью&quot;/&gt;
        ///&lt;Allolog Form=&quot;промышленным&quot;/&gt;
        ///&lt;Allolog Form=&quot;промышленная&quot;/&gt;
        ///&lt;Allolog Form=&quot;промышленном&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string economica_export {
            get {
                return ResourceManager.GetString("economica_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;счаст&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;счастье&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;любов&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;любовь&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;счастлив&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;счастливой&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;эмоциональн&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;эмоциональную&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;любв&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;любви&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;безразличн&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;безразлично&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;сознан&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string etica_le {
            get {
                return ResourceManager.GetString("etica_le", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;танц&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;танцуй&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;громк&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;громко&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;активн&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;активно&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;смея&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;смеяться&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;спрашива&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;спрашивать&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;рассказа&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;рассказать&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;друз&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;друзья [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string extra_ei {
            get {
                return ResourceManager.GetString("extra_ei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;маневр&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;маневры&quot;/&gt;
        ///&lt;Allolog Form=&quot;маневр&quot;/&gt;
        ///&lt;Allolog Form=&quot;маневра&quot;/&gt;
        ///&lt;Allolog Form=&quot;маневров&quot;/&gt;
        ///&lt;Allolog Form=&quot;маневри&quot;/&gt;
        ///&lt;Allolog Form=&quot;маневром&quot;/&gt;
        ///&lt;Allolog Form=&quot;маневру&quot;/&gt;
        ///&lt;Allolog Form=&quot;маневре&quot;/&gt;
        ///&lt;Allolog Form=&quot;маневрами&quot;/&gt;
        ///&lt;Allolog Form=&quot;маневрах&quot;/&gt;
        ///&lt;Allolog Form=&quot;маневрам&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;напоминан&quot; Weight=&quot;0.00114413199758432&quot;&gt;
        ///&lt;Allolog Form=&quot;напоминания&quot;/&gt;
        ///&lt;Allolog Form=&quot;напоминание&quot;/&gt;
        ///&lt;Allolog Form=&quot;напоминаний&quot;/&gt;
        ///&lt;Allo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ezoter_export {
            get {
                return ResourceManager.GetString("Ezoter_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;углекисл&quot; Weight=&quot;0.502819422543036&quot;&gt;
        ///&lt;Allolog Form=&quot;углекислого&quot;/&gt;
        ///&lt;Allolog Form=&quot;углекислый&quot;/&gt;
        ///&lt;Allolog Form=&quot;углекислым&quot;/&gt;
        ///&lt;Allolog Form=&quot;углекислая&quot;/&gt;
        ///&lt;Allolog Form=&quot;углекислом&quot;/&gt;
        ///&lt;Allolog Form=&quot;углекислой&quot;/&gt;
        ///&lt;Allolog Form=&quot;углекислые&quot;/&gt;
        ///&lt;Allolog Form=&quot;углекисло&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;восстановительных&quot; Weight=&quot;0.0573485731427748&quot;&gt;
        ///&lt;Allolog Form=&quot;восстановительных&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;эфир&quot; Weight=&quot;0.544506375903713&quot;&gt;
        ///&lt;Allolog Form=&quot;эфир&quot;/&gt;
        ///&lt;Allolog Form=&quot;эфир [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string himiy_export {
            get {
                return ResourceManager.GetString("himiy_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;памя&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;память&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;слуша&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;слушать&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;личн&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;личное&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;ответствен&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;ответственность&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;собствен&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;собственное&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;услыша&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;услышать&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;забыва&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string intra_ei {
            get {
                return ResourceManager.GetString("intra_ei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;счаст&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;счастье&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;любов&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;любовь&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;друз&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;друзьям&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;прекрасн&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;прекрасный&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;эмоц&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;эмоции&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;эмоциональн&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;эмоциональную&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;любв&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;любви [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string intuit_si {
            get {
                return ResourceManager.GetString("intuit_si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;любя&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;любящий&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;обманыва&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;обманывают&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;музык&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;музыку&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;любит&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;любит&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;тайн&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;тайна&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;красот&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;красоту&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;эмоциональн&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;эмоционал [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string irracional_ri {
            get {
                return ResourceManager.GetString("irracional_ri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;машин&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;машины&quot;/&gt;
        ///&lt;Allolog Form=&quot;машин&quot;/&gt;
        ///&lt;Allolog Form=&quot;машина&quot;/&gt;
        ///&lt;Allolog Form=&quot;машину&quot;/&gt;
        ///&lt;Allolog Form=&quot;машине&quot;/&gt;
        ///&lt;Allolog Form=&quot;машинами&quot;/&gt;
        ///&lt;Allolog Form=&quot;машинах&quot;/&gt;
        ///&lt;Allolog Form=&quot;машиной&quot;/&gt;
        ///&lt;Allolog Form=&quot;машинная&quot;/&gt;
        ///&lt;Allolog Form=&quot;машинам&quot;/&gt;
        ///&lt;Allolog Form=&quot;машинные&quot;/&gt;
        ///&lt;Allolog Form=&quot;машинной&quot;/&gt;
        ///&lt;Allolog Form=&quot;машинном&quot;/&gt;
        ///&lt;Allolog Form=&quot;машинного&quot;/&gt;
        ///&lt;Allolog Form=&quot;машинную&quot;/&gt;
        ///&lt;Allolog Form=&quot;машинности&quot;/&gt;
        ///&lt;Allolog Form=&quot;машинным&quot;/&gt;
        ///&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string it_export {
            get {
                return ResourceManager.GetString("it_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;информац&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;информация&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;сумм&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;сумму&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;фрейд&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;фрейд&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;систем&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;систему&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;доказа&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;доказано&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;функц&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;функцию&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;аргумент&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;аргумент&quot;/&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string logica_le {
            get {
                return ResourceManager.GetString("logica_le", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;адел&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;адель&quot;/&gt;
        ///&lt;Allolog Form=&quot;адели&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;характеристик&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;характеристиках&quot;/&gt;
        ///&lt;Allolog Form=&quot;характеристики&quot;/&gt;
        ///&lt;Allolog Form=&quot;характеристик&quot;/&gt;
        ///&lt;Allolog Form=&quot;характеристика&quot;/&gt;
        ///&lt;Allolog Form=&quot;характеристику&quot;/&gt;
        ///&lt;Allolog Form=&quot;характеристикам&quot;/&gt;
        ///&lt;Allolog Form=&quot;характеристиками&quot;/&gt;
        ///&lt;Allolog Form=&quot;характеристике&quot;/&gt;
        ///&lt;Allolog Form=&quot;характеристикой&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;отношен&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allol [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mathematics_export {
            get {
                return ResourceManager.GetString("mathematics_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;килограмм&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;килограммов&quot;/&gt;
        ///&lt;Allolog Form=&quot;килограмм&quot;/&gt;
        ///&lt;Allolog Form=&quot;килограмма&quot;/&gt;
        ///&lt;Allolog Form=&quot;килограмму&quot;/&gt;
        ///&lt;Allolog Form=&quot;килограммом&quot;/&gt;
        ///&lt;Allolog Form=&quot;килограммах&quot;/&gt;
        ///&lt;Allolog Form=&quot;килограммами&quot;/&gt;
        ///&lt;Allolog Form=&quot;килограммы&quot;/&gt;
        ///&lt;Allolog Form=&quot;килограммам&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;секрет&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;секрет&quot;/&gt;
        ///&lt;Allolog Form=&quot;секрета&quot;/&gt;
        ///&lt;Allolog Form=&quot;секреты&quot;/&gt;
        ///&lt;Allolog Form=&quot;секретов&quot;/&gt;
        ///&lt;Allolog Form=&quot;секретами&quot;/&gt;
        ///&lt;Al [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string medicine_export {
            get {
                return ResourceManager.GetString("medicine_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;аудитор&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;аудиторией&quot;/&gt;
        ///&lt;Allolog Form=&quot;аудитория&quot;/&gt;
        ///&lt;Allolog Form=&quot;аудитории&quot;/&gt;
        ///&lt;Allolog Form=&quot;аудиторий&quot;/&gt;
        ///&lt;Allolog Form=&quot;аудиторию&quot;/&gt;
        ///&lt;Allolog Form=&quot;аудиторам&quot;/&gt;
        ///&lt;Allolog Form=&quot;аудиторов&quot;/&gt;
        ///&lt;Allolog Form=&quot;аудиториях&quot;/&gt;
        ///&lt;Allolog Form=&quot;аудитор&quot;/&gt;
        ///&lt;Allolog Form=&quot;аудиториями&quot;/&gt;
        ///&lt;Allolog Form=&quot;аудиториям&quot;/&gt;
        ///&lt;Allolog Form=&quot;аудиторы&quot;/&gt;
        ///&lt;Allolog Form=&quot;аудитора&quot;/&gt;
        ///&lt;Allolog Form=&quot;аудиториу&quot;/&gt;
        ///&lt;Allolog Form=&quot;аудиторами&quot;/&gt;
        ///&lt;Allolog Form=&quot;аудитором&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string muzica_export {
            get {
                return ResourceManager.GetString("muzica_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;универсал&quot; Weight=&quot;0.0601173888349221&quot;&gt;
        ///&lt;Allolog Form=&quot;универсалов&quot;/&gt;
        ///&lt;Allolog Form=&quot;универсалы&quot;/&gt;
        ///&lt;Allolog Form=&quot;универсаль&quot;/&gt;
        ///&lt;Allolog Form=&quot;универсалий&quot;/&gt;
        ///&lt;Allolog Form=&quot;универсалии&quot;/&gt;
        ///&lt;Allolog Form=&quot;универсалиях&quot;/&gt;
        ///&lt;Allolog Form=&quot;универсалия&quot;/&gt;
        ///&lt;Allolog Form=&quot;универсалиями&quot;/&gt;
        ///&lt;Allolog Form=&quot;универсалию&quot;/&gt;
        ///&lt;Allolog Form=&quot;универсалиям&quot;/&gt;
        ///&lt;Allolog Form=&quot;универсалами&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;сократ&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;сократить&quot;/&gt;
        ///&lt;Allolog Form=&quot;сократила&quot;/&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string philosof_export {
            get {
                return ResourceManager.GetString("philosof_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;инерцион&quot; Weight=&quot;0.0528720730783039&quot;&gt;
        ///&lt;Allolog Form=&quot;инерционного&quot;/&gt;
        ///&lt;Allolog Form=&quot;инерционные&quot;/&gt;
        ///&lt;Allolog Form=&quot;инерционная&quot;/&gt;
        ///&lt;Allolog Form=&quot;инерционность&quot;/&gt;
        ///&lt;Allolog Form=&quot;инерционностью&quot;/&gt;
        ///&lt;Allolog Form=&quot;инерционности&quot;/&gt;
        ///&lt;Allolog Form=&quot;инерционный&quot;/&gt;
        ///&lt;Allolog Form=&quot;инерционным&quot;/&gt;
        ///&lt;Allolog Form=&quot;инерционное&quot;/&gt;
        ///&lt;Allolog Form=&quot;инерционной&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;ультразвук&quot; Weight=&quot;0.0532241448385066&quot;&gt;
        ///&lt;Allolog Form=&quot;ультразвук&quot;/&gt;
        ///&lt;Allolog Form=&quot;ультразвука&quot;/&gt;
        ///&lt;Allo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string phizica_export {
            get {
                return ResourceManager.GetString("phizica_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;культур&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;культура&quot;/&gt;
        ///&lt;Allolog Form=&quot;культуры&quot;/&gt;
        ///&lt;Allolog Form=&quot;культуре&quot;/&gt;
        ///&lt;Allolog Form=&quot;культуру&quot;/&gt;
        ///&lt;Allolog Form=&quot;культурах&quot;/&gt;
        ///&lt;Allolog Form=&quot;культур&quot;/&gt;
        ///&lt;Allolog Form=&quot;культурами&quot;/&gt;
        ///&lt;Allolog Form=&quot;культурам&quot;/&gt;
        ///&lt;Allolog Form=&quot;культурой&quot;/&gt;
        ///&lt;Allolog Form=&quot;культуро&quot;/&gt;
        ///&lt;Allolog Form=&quot;культурою&quot;/&gt;
        ///&lt;Allolog Form=&quot;культури&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;истор&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;история&quot;/&gt;
        ///&lt;Allolog Form=&quot;истории&quot;/&gt;
        ///&lt;Allolog Form=&quot;историю&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string policy_export {
            get {
                return ResourceManager.GetString("policy_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;блог&quot; Weight=&quot;0.00430929660407714&quot;&gt;
        ///&lt;Allolog Form=&quot;блог&quot;/&gt;
        ///&lt;Allolog Form=&quot;блога&quot;/&gt;
        ///&lt;Allolog Form=&quot;блогах&quot;/&gt;
        ///&lt;Allolog Form=&quot;блоге&quot;/&gt;
        ///&lt;Allolog Form=&quot;блоги&quot;/&gt;
        ///&lt;Allolog Form=&quot;блогов&quot;/&gt;
        ///&lt;Allolog Form=&quot;блогами&quot;/&gt;
        ///&lt;Allolog Form=&quot;блогам&quot;/&gt;
        ///&lt;Allolog Form=&quot;блогу&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;покупательск&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;покупательской&quot;/&gt;
        ///&lt;Allolog Form=&quot;покупательского&quot;/&gt;
        ///&lt;Allolog Form=&quot;покупательский&quot;/&gt;
        ///&lt;Allolog Form=&quot;покупательским&quot;/&gt;
        ///&lt;Allolog Form=&quot;покупательские&quot;/&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PR_export {
            get {
                return ResourceManager.GetString("PR_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;характер&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;характером&quot;/&gt;
        ///&lt;Allolog Form=&quot;характер&quot;/&gt;
        ///&lt;Allolog Form=&quot;характера&quot;/&gt;
        ///&lt;Allolog Form=&quot;характеру&quot;/&gt;
        ///&lt;Allolog Form=&quot;характере&quot;/&gt;
        ///&lt;Allolog Form=&quot;характери&quot;/&gt;
        ///&lt;Allolog Form=&quot;характеров&quot;/&gt;
        ///&lt;Allolog Form=&quot;характеры&quot;/&gt;
        ///&lt;Allolog Form=&quot;характерами&quot;/&gt;
        ///&lt;Allolog Form=&quot;характерах&quot;/&gt;
        ///&lt;Allolog Form=&quot;характерам&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;воображен&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;воображение&quot;/&gt;
        ///&lt;Allolog Form=&quot;воображением&quot;/&gt;
        ///&lt;Allolog Form=&quot;воображению&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string psy_export {
            get {
                return ResourceManager.GetString("psy_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;систем&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;систему&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;доказа&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;доказано&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;обнаружива&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;обнаруживайте&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;процесс&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;процесс&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;физик&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;физики&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;эволюц&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;эволюция&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;математик&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Fo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string racional_ri {
            get {
                return ResourceManager.GetString("racional_ri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;рецепт&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;рецепт&quot;/&gt;
        ///&lt;Allolog Form=&quot;рецепты&quot;/&gt;
        ///&lt;Allolog Form=&quot;рецептов&quot;/&gt;
        ///&lt;Allolog Form=&quot;рецепту&quot;/&gt;
        ///&lt;Allolog Form=&quot;рецептом&quot;/&gt;
        ///&lt;Allolog Form=&quot;рецептам&quot;/&gt;
        ///&lt;Allolog Form=&quot;рецепте&quot;/&gt;
        ///&lt;Allolog Form=&quot;рецептами&quot;/&gt;
        ///&lt;Allolog Form=&quot;рецепта&quot;/&gt;
        ///&lt;Allolog Form=&quot;рецептах&quot;/&gt;
        ///&lt;Allolog Form=&quot;рецепти&quot;/&gt;
        ///&lt;Allolog Form=&quot;рецептив&quot;/&gt;
        ///&lt;Allolog Form=&quot;рецепто&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;философ&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;философии&quot;/&gt;
        ///&lt;Allolog Form=&quot;философом&quot;/&gt;
        ///&lt;A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Samosov_export {
            get {
                return ResourceManager.GetString("Samosov_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;соответств&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;соответствующие&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;определен&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;определённым&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;категор&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;категория&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;систем&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;систему&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;доказа&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;доказано&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;мудрец&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;мудреца&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;развит&quot; Weight=&quot;0.5&quot;&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sensor_si {
            get {
                return ResourceManager.GetString("sensor_si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  
        ///.
        ///,
        ///?
        ///;
        ///!
        ///:
        ///(
        ///)
        ///[
        ///]
        ///{
        ///}
        ///$
        ///&quot;
        ///&apos;
        ///
        ///&lt;
        ///&gt;
        ///&quot;.
        /// </summary>
        internal static string Separators {
            get {
                return ResourceManager.GetString("Separators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;мокр&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;мокрой&quot;/&gt;
        ///&lt;Allolog Form=&quot;мокрым&quot;/&gt;
        ///&lt;Allolog Form=&quot;мокрый&quot;/&gt;
        ///&lt;Allolog Form=&quot;мокрого&quot;/&gt;
        ///&lt;Allolog Form=&quot;мокрая&quot;/&gt;
        ///&lt;Allolog Form=&quot;мокром&quot;/&gt;
        ///&lt;Allolog Form=&quot;мокрыми&quot;/&gt;
        ///&lt;Allolog Form=&quot;мокрое&quot;/&gt;
        ///&lt;Allolog Form=&quot;мокрые&quot;/&gt;
        ///&lt;Allolog Form=&quot;мокрую&quot;/&gt;
        ///&lt;Allolog Form=&quot;мокрее&quot;/&gt;
        ///&lt;Allolog Form=&quot;мокро&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;секс&quot; Weight=&quot;0.554082895474088&quot;&gt;
        ///&lt;Allolog Form=&quot;секс&quot;/&gt;
        ///&lt;Allolog Form=&quot;сексе&quot;/&gt;
        ///&lt;Allolog Form=&quot;секса&quot;/&gt;
        ///&lt;Allolog Form=&quot;сексу&quot;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sEX_export {
            get {
                return ResourceManager.GetString("sEX_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;спорт&quot; Weight=&quot;0.640461923652691&quot;&gt;
        ///&lt;Allolog Form=&quot;спорт&quot;/&gt;
        ///&lt;Allolog Form=&quot;спорта&quot;/&gt;
        ///&lt;Allolog Form=&quot;спорте&quot;/&gt;
        ///&lt;Allolog Form=&quot;спорту&quot;/&gt;
        ///&lt;Allolog Form=&quot;спортом&quot;/&gt;
        ///&lt;Allolog Form=&quot;спортив&quot;/&gt;
        ///&lt;Allolog Form=&quot;спортов&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;гонк&quot; Weight=&quot;0.539272026314874&quot;&gt;
        ///&lt;Allolog Form=&quot;гонка&quot;/&gt;
        ///&lt;Allolog Form=&quot;гонках&quot;/&gt;
        ///&lt;Allolog Form=&quot;гонку&quot;/&gt;
        ///&lt;Allolog Form=&quot;гонки&quot;/&gt;
        ///&lt;Allolog Form=&quot;гонкам&quot;/&gt;
        ///&lt;Allolog Form=&quot;гонке&quot;/&gt;
        ///&lt;Allolog Form=&quot;гонкой&quot;/&gt;
        ///&lt;Allolog Form=&quot;гонками&quot;/&gt;
        ///&lt;/Word [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sport_export {
            get {
                return ResourceManager.GetString("sport_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -
        ///еще
        ///него
        ///сказать
        ///а
        ///ж
        ///нее
        ///со
        ///без
        ///же
        ///ней
        ///совсем
        ///более
        ///жизнь
        ///нельзя
        ///так
        ///больше
        ///за
        ///нет
        ///такой
        ///будет
        ///зачем
        ///ни
        ///там
        ///будто
        ///здесь
        ///нибудь
        ///тебя
        ///бы
        ///и
        ///никогда
        ///тем
        ///был
        ///из
        ///ним
        ///теперь
        ///была
        ///из-за
        ///них
        ///то
        ///были
        ///или
        ///ничего
        ///тогда
        ///было
        ///им
        ///но
        ///того
        ///быть
        ///иногда
        ///ну
        ///тоже
        ///в
        ///их
        ///о
        ///только
        ///вам
        ///к
        ///об
        ///том
        ///вас
        ///кажется
        ///один
        ///тот
        ///вдруг
        ///как
        ///он
        ///три
        ///ведь
        ///какая
        ///она
        ///тут
        ///во
        ///какой
        ///они
        ///ты
        ///вот
        ///когда
        ///опять
        ///у
        ///впрочем
        ///конечно
        ///от
        ///уж
        ///все
        ///которого
        ///перед
        ///уже
        ///всегда
        ///которые
        ///по
        ///хорошо
        ///всего
        ///кто
        ///под
        ///хоть
        ///всех
        ///куда
        ///после
        ///чего
        ///всю
        ///ли
        ///потом
        ///ч [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StopWords {
            get {
                return ResourceManager.GetString("StopWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;девушк&quot; Weight=&quot;0.321383690099944&quot;&gt;
        ///&lt;Allolog Form=&quot;девушки&quot;/&gt;
        ///&lt;Allolog Form=&quot;девушкой&quot;/&gt;
        ///&lt;Allolog Form=&quot;девушке&quot;/&gt;
        ///&lt;Allolog Form=&quot;девушку&quot;/&gt;
        ///&lt;Allolog Form=&quot;девушка&quot;/&gt;
        ///&lt;Allolog Form=&quot;девушкам&quot;/&gt;
        ///&lt;Allolog Form=&quot;девушками&quot;/&gt;
        ///&lt;Allolog Form=&quot;девушках&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;клуб&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;клуб&quot;/&gt;
        ///&lt;Allolog Form=&quot;клубы&quot;/&gt;
        ///&lt;Allolog Form=&quot;клубов&quot;/&gt;
        ///&lt;Allolog Form=&quot;клуба&quot;/&gt;
        ///&lt;Allolog Form=&quot;клубе&quot;/&gt;
        ///&lt;Allolog Form=&quot;клубах&quot;/&gt;
        ///&lt;Allolog Form=&quot;клубами&quot;/&gt;
        ///&lt;Allolog [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tp_export {
            get {
                return ResourceManager.GetString("tp_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;семейных&quot; Weight=&quot;0.00167815522854219&quot;&gt;
        ///&lt;Allolog Form=&quot;семейных&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;страхован&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;страхованию&quot;/&gt;
        ///&lt;Allolog Form=&quot;страхование&quot;/&gt;
        ///&lt;Allolog Form=&quot;страхования&quot;/&gt;
        ///&lt;Allolog Form=&quot;страховании&quot;/&gt;
        ///&lt;Allolog Form=&quot;страхованием&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;правительств&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;правительство&quot;/&gt;
        ///&lt;Allolog Form=&quot;правительством&quot;/&gt;
        ///&lt;Allolog Form=&quot;правительства&quot;/&gt;
        ///&lt;Allolog Form=&quot;правительств&quot;/&gt;
        ///&lt;Allolog Form=&quot;правительствам [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ur_export {
            get {
                return ResourceManager.GetString("Ur_export", resourceCulture);
            }
        }
    }
}
