//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextClassifierLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextClassifierLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профессор  Ю.М.Смирнов
        ///
        ///А Н А Л И Т И Ч Е С К А Я   Г Е О М Е Т Р И Я   
        ///
        ///Лекции для первого курса механико-математического факультета МГУ 
        ///( Осень  1997 )
        ///
        ///§  1. Векторы и линейные действия над ними.
        ///
        ///Здесь мы с единой точки зрения подведем итог тому, что известно из школы о векторах. Конечно, при любом изложении основные свойства линейных действий - сложения и умножения на числа - оказываются одинаковыми. Вот они : 
        ///
        ///1)     (a + b) + c = a + (b + c)    ,      2)            a + b = b + a         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _mathematics {
            get {
                return ResourceManager.GetString("_mathematics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///                 2Г А Л И Н А 0   2Ш 0  2А 0  2Л 0  2Ы 0  2Г 0  2И 0  2Н 0  2А
        ///
        ///
        ///
        ///
        ///
        ///
        ///            2Ф И Л О С О Ф И Я    З Д О Р О В Ь Я
        ///
        ///
        ///
        ///           С О В Е Т Ы  Н А  К А Ж Д Ы Й  Д Е Н Ь
        ///
        ///
        ///                И   Н А   В С Ю   Ж И З Н Ь
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///                      Санкт-Петербург
        ///
        ///                            1994
        ///
        ///
        ///
        ///                           - 2 -
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///Ш 18  Шалыгина Г.И.
        ///      Философия здоровья:  советы  на  каждый  день и на всю
        ///жизнь - СПб.:        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _medicine {
            get {
                return ResourceManager.GetString("_medicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другое небо. Ложные стереотипы российской демократии.
        ///	
        ///
        ///   Вазиф Мейланов.
        ///   Другое небо. Ложные стереотипы российской демократии.  Анализ Чеченс-
        ///кого кризиса
        ///
        ///
        ///     Махачкала 1999
        ///
        ///
        ///     Вазиф   Мейланов.  Ложные  стереотипы   российской  демократии.  Анализ
        ///чеченского кризиса. -- Махачкала, 1999. -- 480 с.
        ///
        ///     В книгу  вошли избранные выступления, статьи,  письма и заявления  В.С.
        ///Мейланова  1989--1999  гг.,  материалы  Следственного  дела и  Личного  дела
        ///заключенного.
        ///
        ///     © Copy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _policy {
            get {
                return ResourceManager.GetString("_policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рита Л. Аткинсон, Ричард С. Аткинсон, Эдвард Е. Смит, Дэрил Дж. Бем, Сьюзен Нолен-Хоэксема
        ///
        ///Введение в психологию
        ///Учебник для студентов университетов
        ///
        ///(Rita L. Atkinson, Richard C. Atkinson, Edward E. Smith, Daryl J. Bem, Susan Nolen-Hoeksema. &quot;Hilgard&apos;s Introduction to Psychology. History, Theory, Research, and Applications&quot;, 13th ed., 2000)
        ///
        ///
        ///«Введение в психологию» на протяжении последних 50 лет остается одним из лучших в мире учебных пособий! Читателю предлагается последнее издание этого классич [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _psy {
            get {
                return ResourceManager.GetString("_psy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Танцуй красиво. Бей сильно. Уходи гордо. Не говори о себе громко. Пусть другие о тебе скажут тихо...
        ///Лучший способ скрыть правду — это сказать её в шутку.
        ///Я перестал активно пользоваться социальными сетями! &lt;br&gt;&lt;br&gt;Этот материал я вынашивал очень давно, наверное уже больше месяца. Заранее приношу свои извинения, если изложенное тут кого-то обидит. [club39585115|читать дальше]...
        ///О чём мечтаю я.? &lt;br&gt;мечтаю просто жить... Дышать, любить и знать, что я любима! &lt;br&gt;И каждое мгновение ценить... Поскольку наш [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _tp {
            get {
                return ResourceManager.GetString("_tp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  
        ///.
        ///,
        ///?
        ///;
        ///!
        ///:
        ///(
        ///)
        ///[
        ///]
        ///{
        ///}
        ///$
        ///&quot;
        ///&apos;
        ///
        ///&lt;
        ///&gt;.
        /// </summary>
        internal static string Separators {
            get {
                return ResourceManager.GetString("Separators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -
        ///еще
        ///него
        ///сказать
        ///а
        ///ж
        ///нее
        ///со
        ///без
        ///же
        ///ней
        ///совсем
        ///более
        ///жизнь
        ///нельзя
        ///так
        ///больше
        ///за
        ///нет
        ///такой
        ///будет
        ///зачем
        ///ни
        ///там
        ///будто
        ///здесь
        ///нибудь
        ///тебя
        ///бы
        ///и
        ///никогда
        ///тем
        ///был
        ///из
        ///ним
        ///теперь
        ///была
        ///из-за
        ///них
        ///то
        ///были
        ///или
        ///ничего
        ///тогда
        ///было
        ///им
        ///но
        ///того
        ///быть
        ///иногда
        ///ну
        ///тоже
        ///в
        ///их
        ///о
        ///только
        ///вам
        ///к
        ///об
        ///том
        ///вас
        ///кажется
        ///один
        ///тот
        ///вдруг
        ///как
        ///он
        ///три
        ///ведь
        ///какая
        ///она
        ///тут
        ///во
        ///какой
        ///они
        ///ты
        ///вот
        ///когда
        ///опять
        ///у
        ///впрочем
        ///конечно
        ///от
        ///уж
        ///все
        ///которого
        ///перед
        ///уже
        ///всегда
        ///которые
        ///по
        ///хорошо
        ///всего
        ///кто
        ///под
        ///хоть
        ///всех
        ///куда
        ///после
        ///чего
        ///всю
        ///ли
        ///потом
        ///ч [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StopWords {
            get {
                return ResourceManager.GetString("StopWords", resourceCulture);
            }
        }
    }
}
