//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.269
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextClassifierLib.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextClassifierLib.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///
        ///
        ///Furfur
        ///СТИЛЬ
        /// 
        ///ГЕРОИ
        /// 
        ///КУЛЬТУРА
        /// 
        ///ДЕВУШКИ
        /// 
        ///СПОРТ
        ///ГАРАЖ
        /// 
        ///ГАДЖЕТЫ
        /// 
        ///ЕДА И ВЫПИВКА
        /// 
        ///БЛОГ
        ///Клуб Furfur
        ///Поиск
        ///Войти
        ///Войти через Facebook
        ///Зарегистрироваться
        ///История и разновидности самых мускулистых автомобилей в мире — маслкаров
        ///
        ///Написал Саша Сколков, 9 декабря 2011 года
        ///
        ///377 3 74991
        ///  
        ///Маслкары — это по-настоящему отдельная культура в среде автолюбителей, как и в автомобильной промышленности в целом. Абсолютно все пускай один раз, но видели эти скоростные американские машины  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string auto {
            get {
                return ResourceManager.GetString("auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;гараж&quot; Weight=&quot;0.506824914803941&quot;&gt;
        ///&lt;Allolog Form=&quot;гараж&quot;/&gt;
        ///&lt;Allolog Form=&quot;гаража&quot;/&gt;
        ///&lt;Allolog Form=&quot;гаражи&quot;/&gt;
        ///&lt;Allolog Form=&quot;гараже&quot;/&gt;
        ///&lt;Allolog Form=&quot;гаражах&quot;/&gt;
        ///&lt;Allolog Form=&quot;гаражу&quot;/&gt;
        ///&lt;Allolog Form=&quot;гаражом&quot;/&gt;
        ///&lt;Allolog Form=&quot;гаражей&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;автомобил&quot; Weight=&quot;1.4296789260518&quot;&gt;
        ///&lt;Allolog Form=&quot;автомобилей&quot;/&gt;
        ///&lt;Allolog Form=&quot;автомобиль&quot;/&gt;
        ///&lt;Allolog Form=&quot;автомобиля&quot;/&gt;
        ///&lt;Allolog Form=&quot;автомобилях&quot;/&gt;
        ///&lt;Allolog Form=&quot;автомобилем&quot;/&gt;
        ///&lt;Allolog Form=&quot;автомобилю&quot;/&gt;        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string auto_export {
            get {
                return ResourceManager.GetString("auto_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  
        ///
        ///БИОЛОГИЯ
        ///Под редакцией академика РАМН профессора В.Н. Ярыгина
        ///В двух книгах 
        ///• Книга 1 •
        ///Издание пятое, исправленное и дополненное
        ///Рекомендовано Министерством образования Российской Федерации 
        ///в качестве учебника для студентов медицинских специальностей 
        ///высших учебных заведений
        /// 
        ///Москва «Высшая школа» 2003
        ///УДК 574/578 
        ///ББК 28.0 
        ///Б 63
        ///Авторы:
        ///В.Н. Ярыгин, В.И. Васильева, И.Н. Волков, В.В. Синелыцикова
        ///
        ///Рецензент:
        ///кафедра медицинской биологии и генетики Тверской государственной медицинс [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string biologiy {
            get {
                return ResourceManager.GetString("biologiy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;экологическ&quot; Weight=&quot;0.531776595612708&quot;&gt;
        ///&lt;Allolog Form=&quot;экологические&quot;/&gt;
        ///&lt;Allolog Form=&quot;экологически&quot;/&gt;
        ///&lt;Allolog Form=&quot;экологического&quot;/&gt;
        ///&lt;Allolog Form=&quot;экологических&quot;/&gt;
        ///&lt;Allolog Form=&quot;экологической&quot;/&gt;
        ///&lt;Allolog Form=&quot;экологическое&quot;/&gt;
        ///&lt;Allolog Form=&quot;экологическими&quot;/&gt;
        ///&lt;Allolog Form=&quot;экологическая&quot;/&gt;
        ///&lt;Allolog Form=&quot;экологическую&quot;/&gt;
        ///&lt;Allolog Form=&quot;экологическим&quot;/&gt;
        ///&lt;Allolog Form=&quot;экологический&quot;/&gt;
        ///&lt;Allolog Form=&quot;экологическом&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;выживаем&quot; Weight=&quot;0.0538866 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string biologiy_export {
            get {
                return ResourceManager.GetString("biologiy_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на    їїїїїТатьяна Зорина
        ///	Кулинарная  из FIDO
        ///
        ///
        ///Напитки
        ///Варенья, компоты Заготовки на зиму
        ///Горячее
        ///Пряности, Соусы, приправы
        ///Сладости
        ///Гарниры
        ///Овощи
        ///Блюда в СВЧ
        ///Разное
        ///
        ///
        ///                        Напитки
        ///
        ///
        ///Чеpный кофе.
        ///Безалкогольные коктейли
        ///Квас
        ///Напитки с кофе
        ///Вина
        ///
        ///
        ///                        Кофе
        ///
        ///                                Чеpный кофе.
        ///
        ///1. Для пpиготовления чеpного кофе pекомендуется употpеблять только
        ///натуpальный кофе хоpошего качества. Можно мешать кофе pазличных соpтов.
        ///З [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string culinariy {
            get {
                return ResourceManager.GetString("culinariy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;масл&quot; Weight=&quot;2.32878396460254&quot;&gt;
        ///&lt;Allolog Form=&quot;масл&quot;/&gt;
        ///&lt;Allolog Form=&quot;масло&quot;/&gt;
        ///&lt;Allolog Form=&quot;масла&quot;/&gt;
        ///&lt;Allolog Form=&quot;маслу&quot;/&gt;
        ///&lt;Allolog Form=&quot;масля&quot;/&gt;
        ///&lt;Allolog Form=&quot;маслами&quot;/&gt;
        ///&lt;Allolog Form=&quot;маслом&quot;/&gt;
        ///&lt;Allolog Form=&quot;масле&quot;/&gt;
        ///&lt;Allolog Form=&quot;маслам&quot;/&gt;
        ///&lt;Allolog Form=&quot;масли&quot;/&gt;
        ///&lt;Allolog Form=&quot;маслах&quot;/&gt;
        ///&lt;Allolog Form=&quot;маслов&quot;/&gt;
        ///&lt;Allolog Form=&quot;маслиев&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;килограмм&quot; Weight=&quot;0.0521797370670334&quot;&gt;
        ///&lt;Allolog Form=&quot;килограммов&quot;/&gt;
        ///&lt;Allolog Form=&quot;килограмм&quot;/&gt;        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string culinariy_export {
            get {
                return ResourceManager.GetString("culinariy_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В. П. Большаков
        ///Л. Ф. Новицкая
        ///ОСОБЕННОСТИ КУЛЬТУРЫ В ЕЕ ИСТОРИЧЕСКОМ РАЗВИТИИ
        ///(от зарождения
        ///до эпохи Возрождения)
        ///ББК 71.0 Печатается по решению
        ///Б 76 РИС НовГУ
        ///Рецензенты
        ///доктор философских наук, профессор С. Т. Махлина
        ///кандидат философских наук, доцент В. Д. Лелеко
        ///кандидат философских наук, доцент И. К. Москвина
        ///кандидат философских наук, доцент Н. Н. Суворов
        ///Большаков В. П., Новицкая Л. Ф.
        ///Особенности культуры в ее историческом развитии (от зарождения до эпохи Возрождения): Учебное пособие [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string cultura {
            get {
                return ResourceManager.GetString("cultura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;культур&quot; Weight=&quot;0.971032186039235&quot;&gt;
        ///&lt;Allolog Form=&quot;культура&quot;/&gt;
        ///&lt;Allolog Form=&quot;культуры&quot;/&gt;
        ///&lt;Allolog Form=&quot;культуре&quot;/&gt;
        ///&lt;Allolog Form=&quot;культуру&quot;/&gt;
        ///&lt;Allolog Form=&quot;культурах&quot;/&gt;
        ///&lt;Allolog Form=&quot;культур&quot;/&gt;
        ///&lt;Allolog Form=&quot;культурами&quot;/&gt;
        ///&lt;Allolog Form=&quot;культурам&quot;/&gt;
        ///&lt;Allolog Form=&quot;культурой&quot;/&gt;
        ///&lt;Allolog Form=&quot;культуро&quot;/&gt;
        ///&lt;Allolog Form=&quot;культурою&quot;/&gt;
        ///&lt;Allolog Form=&quot;культури&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;жанр&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;жанра&quot;/&gt;
        ///&lt;Allolog Form=&quot;жанров&quot;/&gt;
        ///&lt;Allolog Form=&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string cultura_export {
            get {
                return ResourceManager.GetString("cultura_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на       АЗБУКА ЭКОНОМИКИ
        ///      Р. Строуп, Дж. Гвартни
        ///
        ///ISBN 5-88662-032-X
        ///  &amp;copy; James D. Gwartney and Richard L. Stroup, &quot;What Everyone Should Know
        ///  About Economics And Prosperty&quot;, 1993
        ///  &amp;copy; Авторизованный русский перевод: Институт национальной модели
        ///  экономики, 1996
        ///Издание является совместным проектом Института национальной модели
        ///экономики и The Fraser Institute, Canada
        ///Руководители проекта М. Бутина и Ю. Кочетыгова.
        ///Авторизованный перевод: Ю. Кочетыгова, В. Найшуль
        ///Редакция: В. Бойко [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string economica {
            get {
                return ResourceManager.GetString("economica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;промышлен&quot; Weight=&quot;0.579283652368774&quot;&gt;
        ///&lt;Allolog Form=&quot;промышленности&quot;/&gt;
        ///&lt;Allolog Form=&quot;промышленно&quot;/&gt;
        ///&lt;Allolog Form=&quot;промышленность&quot;/&gt;
        ///&lt;Allolog Form=&quot;промышленного&quot;/&gt;
        ///&lt;Allolog Form=&quot;промышленные&quot;/&gt;
        ///&lt;Allolog Form=&quot;промышленное&quot;/&gt;
        ///&lt;Allolog Form=&quot;промышленными&quot;/&gt;
        ///&lt;Allolog Form=&quot;промышленной&quot;/&gt;
        ///&lt;Allolog Form=&quot;промышлен&quot;/&gt;
        ///&lt;Allolog Form=&quot;промышленностью&quot;/&gt;
        ///&lt;Allolog Form=&quot;промышленным&quot;/&gt;
        ///&lt;Allolog Form=&quot;промышленная&quot;/&gt;
        ///&lt;Allolog Form=&quot;промышленном&quot;/&gt;
        ///&lt;Allolog Form=&quot;промышленный&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string economica_export {
            get {
                return ResourceManager.GetString("economica_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///Лекции по органической химии.
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///Органическая химия проникла практически во все отрасли народного хозяйства, в том числе и в такую область, как производство строительных материалов, строительных изделий и конструкции. Возникла новая отрасль строительной индустрии, связанная с использованием продуктов органического синтеза.
        ///Основным элементом, входящим в состав органических соединений, является углерод. Поэтому А.М. Бутлеров определил орган [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string himiy {
            get {
                return ResourceManager.GetString("himiy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;углекисл&quot; Weight=&quot;0.506778743623983&quot;&gt;
        ///&lt;Allolog Form=&quot;углекислого&quot;/&gt;
        ///&lt;Allolog Form=&quot;углекислый&quot;/&gt;
        ///&lt;Allolog Form=&quot;углекислым&quot;/&gt;
        ///&lt;Allolog Form=&quot;углекислая&quot;/&gt;
        ///&lt;Allolog Form=&quot;углекислые&quot;/&gt;
        ///&lt;Allolog Form=&quot;углекисло&quot;/&gt;
        ///&lt;Allolog Form=&quot;углекислом&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;восстановительных&quot; Weight=&quot;0.0573087218112957&quot;&gt;
        ///&lt;Allolog Form=&quot;восстановительных&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;эфир&quot; Weight=&quot;0.56001688002511&quot;&gt;
        ///&lt;Allolog Form=&quot;эфир&quot;/&gt;
        ///&lt;Allolog Form=&quot;эфиров&quot;/&gt;
        ///&lt;Allolog Form=&quot;эфиром&quot;/&gt; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string himiy_export {
            get {
                return ResourceManager.GetString("himiy_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;пуска&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;пускай&quot;/&gt;
        ///&lt;Allolog Form=&quot;пускается&quot;/&gt;
        ///&lt;Allolog Form=&quot;пускайте&quot;/&gt;
        ///&lt;Allolog Form=&quot;пускаемый&quot;/&gt;
        ///&lt;Allolog Form=&quot;пускать&quot;/&gt;
        ///&lt;Allolog Form=&quot;пускавшийся&quot;/&gt;
        ///&lt;Allolog Form=&quot;пускался&quot;/&gt;
        ///&lt;Allolog Form=&quot;пускают&quot;/&gt;
        ///&lt;Allolog Form=&quot;пускает&quot;/&gt;
        ///&lt;Allolog Form=&quot;пускаться&quot;/&gt;
        ///&lt;Allolog Form=&quot;пускали&quot;/&gt;
        ///&lt;Allolog Form=&quot;пускалась&quot;/&gt;
        ///&lt;Allolog Form=&quot;пускаются&quot;/&gt;
        ///&lt;Allolog Form=&quot;пускайтесь&quot;/&gt;
        ///&lt;Allolog Form=&quot;пускала&quot;/&gt;
        ///&lt;Allolog Form=&quot;пускающий&quot;/&gt;
        ///&lt;Allolog Form=&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string it_export {
            get {
                return ResourceManager.GetString("it_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///МАТЕМАТИКА
        ///
        ///Тема 1. Роль математики в современном мире. Основные этапы становления математики.
        ///Тема 2. Аксиоматический метод построения научной теории. «Начала» Евклида – образец научного метода. История создания неевклидовой геометрии.
        ///Тема 3. История развития науки о числе . Комплексные числа и действия с ними. Геометрическая интерпретация комплексного числа.
        ///Тема 4. Аналитическая геометрия. Координатный метод. Прямая линия на плоскости.
        ///Тема 5. Кривые второго порядка.
        ///Тема 6. Элементы линейной а [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string mathematics {
            get {
                return ResourceManager.GetString("mathematics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;адел&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;адель&quot;/&gt;
        ///&lt;Allolog Form=&quot;адели&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;характеристик&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;характеристиках&quot;/&gt;
        ///&lt;Allolog Form=&quot;характеристики&quot;/&gt;
        ///&lt;Allolog Form=&quot;характеристик&quot;/&gt;
        ///&lt;Allolog Form=&quot;характеристика&quot;/&gt;
        ///&lt;Allolog Form=&quot;характеристику&quot;/&gt;
        ///&lt;Allolog Form=&quot;характеристикам&quot;/&gt;
        ///&lt;Allolog Form=&quot;характеристиками&quot;/&gt;
        ///&lt;Allolog Form=&quot;характеристике&quot;/&gt;
        ///&lt;Allolog Form=&quot;характеристикой&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;отношен&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allol [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string mathematics_export {
            get {
                return ResourceManager.GetString("mathematics_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ГОУ ВПО ПГМА им. ак. Е. А. Вагнера Росздрава
        ///Кафедра нервных болезней лечебного факультета им. ак. Первушина
        ///
        ///Заведующий кафедрой:
        ///Профессор ШУТОВ А.А.
        ///
        ///Преподаватель:
        ///К. м. н., асс. СЕЛЯНИНА Н. В.
        ///
        ///
        ///
        ///
        ///ИСТОРИЯ БОЛЕЗНИ
        ///Белоусовой Фаины Леонидовны
        ///Клинический диагноз:
        ///Основной: Цереброваскулярная болезнь, гипертоническая болезнь III ст., состояние после удаления хронических гематом в теменной области с двух сторон, последствия острого нарушения мозгового кровообращения в бассейне левой средней  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string medicine {
            get {
                return ResourceManager.GetString("medicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;килограмм&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;килограммов&quot;/&gt;
        ///&lt;Allolog Form=&quot;килограмм&quot;/&gt;
        ///&lt;Allolog Form=&quot;килограмму&quot;/&gt;
        ///&lt;Allolog Form=&quot;килограмма&quot;/&gt;
        ///&lt;Allolog Form=&quot;килограммом&quot;/&gt;
        ///&lt;Allolog Form=&quot;килограммами&quot;/&gt;
        ///&lt;Allolog Form=&quot;килограммах&quot;/&gt;
        ///&lt;Allolog Form=&quot;килограммы&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;секрет&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;секрет&quot;/&gt;
        ///&lt;Allolog Form=&quot;секрета&quot;/&gt;
        ///&lt;Allolog Form=&quot;секреты&quot;/&gt;
        ///&lt;Allolog Form=&quot;секретов&quot;/&gt;
        ///&lt;Allolog Form=&quot;секретом&quot;/&gt;
        ///&lt;Allolog Form=&quot;секретами&quot;/&gt;
        ///&lt;Allol [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string medicine_export {
            get {
                return ResourceManager.GetString("medicine_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///Реферат на тему:
        ///“...Мне не стало хватать его...”
        ///(о творчестве В.С.Высоцкого)
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///					Студента 16 группы ММУ №24
        ///Соловьева Андрея
        ///Преподаватель: Клейменова Е. А.
        ///1996 год
        ///
        ///
        ///ВЛАДИМИР ВЫСОЦКИЙ
        ///(25/I/1938 - 25/VII/1980)
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///					
        ///					Я не люблю фатального исхода,
        ///					От жизни никогда не устаю.
        ///					Я не люблю любое время года,
        ///					Когда веселых песен не пою...
        ///
        ///									В. Высоцкий
        ///
        ///
        ///ВЛАДИМИР ВЫСОЦКИЙ
        ///(25/I/1938 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string muzica {
            get {
                return ResourceManager.GetString("muzica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;аудитор&quot; Weight=&quot;0.0549576566711698&quot;&gt;
        ///&lt;Allolog Form=&quot;аудиторией&quot;/&gt;
        ///&lt;Allolog Form=&quot;аудитории&quot;/&gt;
        ///&lt;Allolog Form=&quot;аудитория&quot;/&gt;
        ///&lt;Allolog Form=&quot;аудиторий&quot;/&gt;
        ///&lt;Allolog Form=&quot;аудиторию&quot;/&gt;
        ///&lt;Allolog Form=&quot;аудиторам&quot;/&gt;
        ///&lt;Allolog Form=&quot;аудиторов&quot;/&gt;
        ///&lt;Allolog Form=&quot;аудиториях&quot;/&gt;
        ///&lt;Allolog Form=&quot;аудитор&quot;/&gt;
        ///&lt;Allolog Form=&quot;аудиториу&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;track&quot; Weight=&quot;0.503232647150098&quot;&gt;
        ///&lt;Allolog Form=&quot;track&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;coupe&quot; Weight=&quot;0.055966832786699&quot;&gt;
        ///&lt;Allolog Form=&quot;co [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string muzica_export {
            get {
                return ResourceManager.GetString("muzica_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сборник
        ///Перспективы метафизики. Классическая и неклассическая метафизика на рубеже веков. СПб, 1997
        ///
        ///Материалы международной конференции Санкт-Петербург, 28-29 октября 1997 г.
        ///
        ///Санкт-Петербургское отделение Института человека РАН
        ///
        ///Философский факультет СПбГУ
        ///
        ///СПб филиал ИИЕТ РАН
        ///
        ///Международная кафедра (ЮНЕСКО) по философии и этике в Санкт-Петербурге
        ///
        ///Балтийский государственный технический университет (ВОЕНМЕХ)
        ///
        ///Отв. редактор сборника - М.С. Уваров
        ///
        ///Издание подготовлено при поддержке Российс [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string philosof {
            get {
                return ResourceManager.GetString("philosof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;универсал&quot; Weight=&quot;0.0600926758047727&quot;&gt;
        ///&lt;Allolog Form=&quot;универсалов&quot;/&gt;
        ///&lt;Allolog Form=&quot;универсалы&quot;/&gt;
        ///&lt;Allolog Form=&quot;универсаль&quot;/&gt;
        ///&lt;Allolog Form=&quot;универсалий&quot;/&gt;
        ///&lt;Allolog Form=&quot;универсалии&quot;/&gt;
        ///&lt;Allolog Form=&quot;универсалиях&quot;/&gt;
        ///&lt;Allolog Form=&quot;универсалия&quot;/&gt;
        ///&lt;Allolog Form=&quot;универсалиями&quot;/&gt;
        ///&lt;Allolog Form=&quot;универсалию&quot;/&gt;
        ///&lt;Allolog Form=&quot;универсалиям&quot;/&gt;
        ///&lt;Allolog Form=&quot;универсалами&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;сократ&quot; Weight=&quot;0.0570117133751901&quot;&gt;
        ///&lt;Allolog Form=&quot;сократить&quot;/&gt;
        ///&lt;Allolog Form= [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string philosof_export {
            get {
                return ResourceManager.GetString("philosof_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на А. И. КИТАЙГОРОДСКИЙ 
        ///ВВЕДЕНИЕ 
        ///В ФИЗИКУ 
        ///Допущено Министерством 
        ///высшего и среднего образования СССР 
        ///в качестве учебного пособия 
        ///студентов высших технических учебных заведений 
        ///ИЗДАТЕЛЬСТВО «НАУКА» 
        ///ГЛАВНАЯ РЕДАКЦИЯ 
        ///ФИЗИКО-МАТЕМАТИЧЕСКОЙ ЛИТЕРАТУРЫ 
        ///МОСКВ А 1 973 
        ///530.1 
        ///К 45 
        ///УДК 530 @75.8) 
        ///Введение в физику. А. И. Китайгородский. 
        ///Изд-во «Наука», Главная редакция физико-математиче- 
        ///физико-математической литературы, 1973. 
        ///Книга представляет собой учебное пособие по физике 
        ///для студ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string phizica {
            get {
                return ResourceManager.GetString("phizica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;инерцион&quot; Weight=&quot;0.0528720730783039&quot;&gt;
        ///&lt;Allolog Form=&quot;инерционного&quot;/&gt;
        ///&lt;Allolog Form=&quot;инерционные&quot;/&gt;
        ///&lt;Allolog Form=&quot;инерционная&quot;/&gt;
        ///&lt;Allolog Form=&quot;инерционность&quot;/&gt;
        ///&lt;Allolog Form=&quot;инерционностью&quot;/&gt;
        ///&lt;Allolog Form=&quot;инерционности&quot;/&gt;
        ///&lt;Allolog Form=&quot;инерционный&quot;/&gt;
        ///&lt;Allolog Form=&quot;инерционным&quot;/&gt;
        ///&lt;Allolog Form=&quot;инерционное&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;ультразвук&quot; Weight=&quot;0.0532241448385066&quot;&gt;
        ///&lt;Allolog Form=&quot;ультразвук&quot;/&gt;
        ///&lt;Allolog Form=&quot;ультразвука&quot;/&gt;
        ///&lt;Allolog Form=&quot;ультразвуки&quot;/&gt;
        ///&lt;/Wor [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string phizica_export {
            get {
                return ResourceManager.GetString("phizica_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Другое небо. Ложные стереотипы российской демократии.
        ///	
        ///
        ///   Вазиф Мейланов.
        ///   Другое небо. Ложные стереотипы российской демократии.  Анализ Чеченс-
        ///кого кризиса
        ///
        ///
        ///     Махачкала 1999
        ///
        ///
        ///     Вазиф   Мейланов.  Ложные  стереотипы   российской  демократии.  Анализ
        ///чеченского кризиса. -- Махачкала, 1999. -- 480 с.
        ///
        ///     В книгу  вошли избранные выступления, статьи,  письма и заявления  В.С.
        ///Мейланова  1989--1999  гг.,  материалы  Следственного  дела и  Личного  дела
        ///заключенного.
        ///
        ///     © Copy [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string policy {
            get {
                return ResourceManager.GetString("policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;культур&quot; Weight=&quot;0.05&quot;&gt;
        ///&lt;Allolog Form=&quot;культура&quot;/&gt;
        ///&lt;Allolog Form=&quot;культуры&quot;/&gt;
        ///&lt;Allolog Form=&quot;культуре&quot;/&gt;
        ///&lt;Allolog Form=&quot;культуру&quot;/&gt;
        ///&lt;Allolog Form=&quot;культурах&quot;/&gt;
        ///&lt;Allolog Form=&quot;культур&quot;/&gt;
        ///&lt;Allolog Form=&quot;культурами&quot;/&gt;
        ///&lt;Allolog Form=&quot;культурам&quot;/&gt;
        ///&lt;Allolog Form=&quot;культурой&quot;/&gt;
        ///&lt;Allolog Form=&quot;культуро&quot;/&gt;
        ///&lt;Allolog Form=&quot;культурою&quot;/&gt;
        ///&lt;Allolog Form=&quot;культури&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;истор&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;история&quot;/&gt;
        ///&lt;Allolog Form=&quot;истории&quot;/&gt;
        ///&lt;Allolog Form=&quot;историю&quot;/ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string policy_export {
            get {
                return ResourceManager.GetString("policy_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///
        ///
        ///Годфруа Ж.
        ///Г59    
        ///Что такое психология: В 2-х т. Т. 1: Пер. с франц.-М.: Мир 1992.-496 с., ил.
        ///ISBN 5-03-001901-4
        ///
        ///
        ///
        ///
        ///Книга канадского автора. Учебник общей психологии с основами физиологии высшей нервной деятельности. В первом томе рассмотрены подходы и методы психологии сознания эмоции и мотивации, научение, память, интеллект и творчество.
        ///Для студентов-биологов, психологов, медиков, педагогов-и всех читателей итересующихся вопросами психологии
        ///Редакции lumepamypbi no биологии
        ///© 1988 Pie [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string psy {
            get {
                return ResourceManager.GetString("psy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;характер&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;характером&quot;/&gt;
        ///&lt;Allolog Form=&quot;характер&quot;/&gt;
        ///&lt;Allolog Form=&quot;характера&quot;/&gt;
        ///&lt;Allolog Form=&quot;характеру&quot;/&gt;
        ///&lt;Allolog Form=&quot;характере&quot;/&gt;
        ///&lt;Allolog Form=&quot;характери&quot;/&gt;
        ///&lt;Allolog Form=&quot;характеров&quot;/&gt;
        ///&lt;Allolog Form=&quot;характеры&quot;/&gt;
        ///&lt;Allolog Form=&quot;характерами&quot;/&gt;
        ///&lt;Allolog Form=&quot;характерах&quot;/&gt;
        ///&lt;Allolog Form=&quot;характерам&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;воображен&quot; Weight=&quot;0.506796323490175&quot;&gt;
        ///&lt;Allolog Form=&quot;воображение&quot;/&gt;
        ///&lt;Allolog Form=&quot;воображению&quot;/&gt;
        ///&lt;Allolog Form=&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string psy_export {
            get {
                return ResourceManager.GetString("psy_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  
        ///.
        ///,
        ///?
        ///;
        ///!
        ///:
        ///(
        ///)
        ///[
        ///]
        ///{
        ///}
        ///$
        ///&quot;
        ///&apos;
        ///
        ///&lt;
        ///&gt;
        ///&quot;.
        /// </summary>
        internal static string separators {
            get {
                return ResourceManager.GetString("separators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на МПС РФ
        ///ЧИПС УрГУПС
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///Реферат по физкультуре
        ///Тема: «Волейбол»
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///Выполнил: 	студент 17-А группы Горьков Е.А.
        ///Проверил: 	Плотников В.М.
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///Челябинск
        ///2001
        /// 
        ///План:
        ///1. ПРАВИЛА   ИГРЫ	1
        ///2.  ИЗУЧЕНИЕ   ТЕХНИКИ   ИГРЫ	1
        ///2.1.   Техника   нападения	2
        ///2.1.1.  Перемещения.	2
        ///2.1.2.   Подачи	2
        ///2.1.3.	Передачи.	3
        ///2.1.4. Нападающие удары	4
        ///2.2.  Техника  защиты	5
        ///2.2.1. Прием  мяча.	5
        ///3. ВЫВОД  ПО  РАБОТЕ	5
        ///4.  СПИСОК   ИСПОЛЬЗУЕМО [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string sport {
            get {
                return ResourceManager.GetString("sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;спорт&quot; Weight=&quot;0.690496729196167&quot;&gt;
        ///&lt;Allolog Form=&quot;спорт&quot;/&gt;
        ///&lt;Allolog Form=&quot;спорта&quot;/&gt;
        ///&lt;Allolog Form=&quot;спорте&quot;/&gt;
        ///&lt;Allolog Form=&quot;спорту&quot;/&gt;
        ///&lt;Allolog Form=&quot;спортом&quot;/&gt;
        ///&lt;Allolog Form=&quot;спортив&quot;/&gt;
        ///&lt;Allolog Form=&quot;спортов&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;гонк&quot; Weight=&quot;0.542488572374006&quot;&gt;
        ///&lt;Allolog Form=&quot;гонка&quot;/&gt;
        ///&lt;Allolog Form=&quot;гонках&quot;/&gt;
        ///&lt;Allolog Form=&quot;гонку&quot;/&gt;
        ///&lt;Allolog Form=&quot;гонки&quot;/&gt;
        ///&lt;Allolog Form=&quot;гонкам&quot;/&gt;
        ///&lt;Allolog Form=&quot;гонке&quot;/&gt;
        ///&lt;Allolog Form=&quot;гонкой&quot;/&gt;
        ///&lt;Allolog Form=&quot;гонками&quot;/&gt;
        ///&lt;/Word [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string sport_export {
            get {
                return ResourceManager.GetString("sport_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на -
        ///еще
        ///него
        ///сказать
        ///а
        ///ж
        ///нее
        ///со
        ///без
        ///же
        ///ней
        ///совсем
        ///более
        ///жизнь
        ///нельзя
        ///так
        ///больше
        ///за
        ///нет
        ///такой
        ///будет
        ///зачем
        ///ни
        ///там
        ///будто
        ///здесь
        ///нибудь
        ///тебя
        ///бы
        ///и
        ///никогда
        ///тем
        ///был
        ///из
        ///ним
        ///теперь
        ///была
        ///из-за
        ///них
        ///то
        ///были
        ///или
        ///ничего
        ///тогда
        ///было
        ///им
        ///но
        ///того
        ///быть
        ///иногда
        ///ну
        ///тоже
        ///в
        ///их
        ///о
        ///только
        ///вам
        ///к
        ///об
        ///том
        ///вас
        ///кажется
        ///один
        ///тот
        ///вдруг
        ///как
        ///он
        ///три
        ///ведь
        ///какая
        ///она
        ///тут
        ///во
        ///какой
        ///они
        ///ты
        ///вот
        ///когда
        ///опять
        ///у
        ///впрочем
        ///конечно
        ///от
        ///уж
        ///все
        ///которого
        ///перед
        ///уже
        ///всегда
        ///которые
        ///по
        ///хорошо
        ///всего
        ///кто
        ///под
        ///хоть
        ///всех
        ///куда
        ///после
        ///чего
        ///всю
        ///ли
        ///потом
        ///ч [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string stopwords {
            get {
                return ResourceManager.GetString("stopwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Танцуй красиво. Бей сильно. Уходи гордо. Не говори о себе громко. Пусть другие о тебе скажут тихо...
        ///Лучший способ скрыть правду — это сказать её в шутку.
        ///Я перестал активно пользоваться социальными сетями! &lt;br&gt;&lt;br&gt;Этот материал я вынашивал очень давно, наверное уже больше месяца. Заранее приношу свои извинения, если изложенное тут кого-то обидит. [club39585115|читать дальше]...
        ///О чём мечтаю я.? &lt;br&gt;мечтаю просто жить... Дышать, любить и знать, что я любима! &lt;br&gt;И каждое мгновение ценить... Поскольку наш [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string tp {
            get {
                return ResourceManager.GetString("tp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Words&gt;
        ///
        ///&lt;Word Stem=&quot;девушк&quot; Weight=&quot;0.517965616091882&quot;&gt;
        ///&lt;Allolog Form=&quot;девушки&quot;/&gt;
        ///&lt;Allolog Form=&quot;девушкой&quot;/&gt;
        ///&lt;Allolog Form=&quot;девушке&quot;/&gt;
        ///&lt;Allolog Form=&quot;девушку&quot;/&gt;
        ///&lt;Allolog Form=&quot;девушка&quot;/&gt;
        ///&lt;Allolog Form=&quot;девушкам&quot;/&gt;
        ///&lt;Allolog Form=&quot;девушками&quot;/&gt;
        ///&lt;Allolog Form=&quot;девушках&quot;/&gt;
        ///&lt;/Word&gt;
        ///
        ///&lt;Word Stem=&quot;клуб&quot; Weight=&quot;0.5&quot;&gt;
        ///&lt;Allolog Form=&quot;клуб&quot;/&gt;
        ///&lt;Allolog Form=&quot;клубы&quot;/&gt;
        ///&lt;Allolog Form=&quot;клубов&quot;/&gt;
        ///&lt;Allolog Form=&quot;клубе&quot;/&gt;
        ///&lt;Allolog Form=&quot;клубах&quot;/&gt;
        ///&lt;Allolog Form=&quot;клуба&quot;/&gt;
        ///&lt;Allolog Form=&quot;клубами&quot;/&gt;
        ///&lt;Allolog  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string tp_export {
            get {
                return ResourceManager.GetString("tp_export", resourceCulture);
            }
        }
    }
}
